# Generated by Django 4.2 on 2023-05-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_portfolio_alter_testimonies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/portfolio')),
                ('url', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.AlterModelOptions(
            name='testimonies',
            options={'verbose_name': 'Testimonies', 'verbose_name_plural': 'Testimonies'},
        ),
    ]
