# Generated by Django 4.2 on 2023-05-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_contact_contacts_alter_contacts_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Talk',
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'Talk', 'verbose_name_plural': 'Talk'},
        ),
    ]
